### PR TITLE
Removed config for DSH

### PR DESCRIPTION
**Pull request by jonnysamps**
@johnmendonca review please? And does this need a migration as well?

### CODE REVIEW

**Comment by johnmendonca** [comment]
:+1:  Yeah pretty sure you will need to delete all RemoteApp of type dsh

**Comment by jonnysamps** [comment]
Ok, thanks John

On Wed, Nov 11, 2015 at 11:44 AM, John Mendonca <notifications@github.com>
wrote:

> [image: :+1:] Yeah pretty sure you will need to delete all RemoteApp of
> type dsh
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/G5/g5-configurator/pull/63#issuecomment-155890236>.
>



-- 
Jonathan

**Comment by jonnysamps** [comment]
@johnmendonca I added a migration to remove the remote apps for dashboard. Can you pull this PR into your regular release process?

**Comment by quady** [comment]
Ran a test on T1 and no dsh was spun up. :+1:

**Pull request merged**
